//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stokTakipEntities : DbContext
    {
        public stokTakipEntities()
            : base("name=stokTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Demirbaslar> Demirbaslars { get; set; }
        public virtual DbSet<DemirbasTurleri> DemirbasTurleris { get; set; }
        public virtual DbSet<Departmanlar> Departmanlars { get; set; }
        public virtual DbSet<Fakulteler> Fakultelers { get; set; }
        public virtual DbSet<OdaDemirbasTablosu> OdaDemirbasTablosus { get; set; }
        public virtual DbSet<Odalar> Odalars { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<v_odaDemirbas> v_odaDemirbas { get; set; }
        public virtual DbSet<v_demirbassayisi> v_demirbassayisi { get; set; }
    }
}
