//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demirbaslar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demirbaslar()
        {
            this.OdaDemirbasTablosus = new HashSet<OdaDemirbasTablosu>();
        }
    
        public int DemirbasID { get; set; }
        public string DemirbasAdi { get; set; }
        public Nullable<int> DemirbasAdet { get; set; }
        public Nullable<System.DateTime> AlimTarihi { get; set; }
        public Nullable<int> DemirbasTurID { get; set; }
        public string DemirbasKodu { get; set; }
        public Nullable<double> Fiyat { get; set; }
    
        public virtual DemirbasTurleri DemirbasTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdaDemirbasTablosu> OdaDemirbasTablosus { get; set; }
    }
}
