//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaDemirbasTablosu
    {
        public int OdaDemirbasID { get; set; }
        public Nullable<int> OdaID { get; set; }
        public Nullable<int> DemirbasID { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Demirbaslar Demirbaslar { get; set; }
        public virtual Odalar Odalar { get; set; }
    }
}
