//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odalar()
        {
            this.OdaDemirbasTablosus = new HashSet<OdaDemirbasTablosu>();
        }
    
        public int OdaID { get; set; }
        public string OdaAdi { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public int FakulteID { get; set; }
        public int DepartmanID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdaDemirbasTablosu> OdaDemirbasTablosus { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Fakulteler Fakulteler { get; set; }
    }
}
