//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_odalaraDemirbasEkleDemirbaslar
    {
        public int DemirbasID { get; set; }
        public string FakulteAdi { get; set; }
        public string DepartmanAdi { get; set; }
        public string DemirbasKodu { get; set; }
        public string DemirbasAdi { get; set; }
        public string DemirbasTurAdi { get; set; }
        public Nullable<int> DemirbasAdet { get; set; }
        public Nullable<double> Fiyat { get; set; }
    }
}
