//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OdaDemirbasListesi
    {
        public v_OdaDemirbasListesi(string odaadi,int odaid,string fakulteadi,string departmanadi,string personel,int ODID,string demirbaskod,string demirbasAd,int adet)
        {
            this.OdaAdi = odaadi;
            this.OdaID = odaid;
            this.FakulteAdi = fakulteadi;
            this.DepartmanAdi = departmanadi;
            this.PersonelAdi = personel;
            this.OdaDemirbasID = ODID;
            this.DemirbasKodu = demirbaskod;
            this.DemirbasAdi = demirbasAd;
            this.Adet = adet;
        }
        public v_OdaDemirbasListesi()
        {

        }
        public string OdaAdi { get; set; }
        public int OdaID { get; set; }
        public string FakulteAdi { get; set; }
        public string DepartmanAdi { get; set; }
        public string PersonelAdi { get; set; }
        public int OdaDemirbasID { get; set; }
        public string DemirbasKodu { get; set; }
        public string DemirbasAdi { get; set; }
        public int Adet { get; set; }
    }
}
