//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OdaDemirbasListesiOdalar
    {
        public string OdaAdi { get; set; }
        public string FakulteAdi { get; set; }
        public string DepartmanAdi { get; set; }
        public string PersonelAdi { get; set; }
        public int OdaID { get; set; }
    }
}
