//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_odaDemirbas
    {
        public int OdaDemirbasID { get; set; }
        public string DemirbasKodu { get; set; }
        public string DemirbasAdi { get; set; }
        public Nullable<int> Adet { get; set; }
        public string PersonelAdi { get; set; }
        public string OdaAdi { get; set; }
        public int PersonelID { get; set; }
    }
}
